### ISSUE TITLE
Better environment vars solution

### ISSUE THREAD

**Issue by lithin** [jameshopkins/httpmark#26]
At the moment, env variables need to be specified in .bashrc or similar. 

Ideally, for aws api id and key, it should be using aws credentials (with the ability to specify --profile when running any command).

The rest of the env variables could come from .env

**Comment by lpil** [comment]
Can just use `.env` the old fashioned way in the mean time

```sh
set -a       # Auto export vars
source .env  # Load vars from .env file
```

**Comment by jameshopkins** [comment]
Yep, or similarly [`direnv`](http://direnv.net/) is a good alternative to allow environment variables that are scoped to the project directory.

Appreciate this may not be ideal for some, but feel we should let the deployment/build process drive out this interface. If it differs greatly for what we require for local development, then we should address it then.
