### ISSUE TITLE
Come Up With A Better Project Name

### ISSUE THREAD

**Issue by jameshopkins** [jameshopkins/httpmark#38]
`webapptest` is a bit 🎺, and we should come up with something better. Currently ideas:

- `benchmark` - Me
- `bench` - @charypar 
- `webmark` - @jonsharratt 

Should try and come up with a bit more, before we open source this; which I'm keen to do very soon, so we can try out [CodeFresh](https://codefresh.io/) for CI for free, as well as other SaaSs

**Comment by charypar** [comment]
"httpmark"? Kinda like 3dmark

**Comment by jameshopkins** [comment]
Great shout @charypar. It's done!

**Comment by lpil** [comment]
Sounds like a http client to me

**Comment by lpil** [comment]
How do you pronounce it?

**Comment by charypar** [comment]
@lpil age-tea-tea-pea-rank

**Comment by lpil** [comment]
Ima call it Hu-prank

**Comment by jonsharratt** [comment]
![](http://r67.cooltext.com/rendered/cooltext217715279146150.gif)

**Comment by charypar** [comment]
@jonsharratt Thanks, that's the logo sorted
